config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/reminders")
  resources :reminders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  validates :name, :color, :date, presence: true
  validates_format_of :color, with: /\A#?(?:[A-F\d]{3}){1,2}\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def index
    start_date = params[:start_date] ? params[:start_date].to_date : Date.today
    range = (start_date - 1.month)..(start_date + 1.month)
    @reminders = Reminder.where(date: range).order(date: :desc)
  end

  def new
    day = params[:day]
    @day = day.nil? ? DateTime.now : day.to_datetime
    render :partial => "new"
  end

  def create
    @reminder = Reminder.new(reminder_params)
    if @reminder.valid?
      @reminder.save
      flash[:notice] = "Reminder created successfully"
    else
      flash[:errors] = @reminder.errors.full_messages
    end
    redirect_to reminders_path
  end

  def edit
    @reminder = Reminder.find(params[:id])
    render :partial => "edit"
  end

  def update
    @reminder = Reminder.find(params[:id])
    if @reminder.update(reminder_params)
      flash[:notice] = "Reminder updated successfully"
    else
      flash[:errors] = @reminder.errors.full_messages
    end
    redirect_to reminders_path
  end

  def destroy
    @reminder = Reminder.find(params[:id])
    @reminder.destroy
    flash[:notice] = "Reminder deleted successfully"
    redirect_to reminders_path
  end

  private

  def reminder_params
    params.require(:reminder).permit(:name, :observation, :color, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(options = {}, &block)
    Calendar.new(self, options).render(&block)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reminders/_edit.html.erb
<div class="modal-dialog" role="document">
  <%= bootstrap_form_for(:reminder, method: "patch", :url => url_for(:controller => 'reminders', :action => 'update', id: @reminder.id) ) do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Update reminder</h5>
        <button type="button" class="btn close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= f.text_field :name, required: true, maxlength: "30", value: @reminder.name %>
        <%= f.color_field :color, required: true, value: @reminder.color %>
        <%= f.datetime_field :date, value: @reminder.date.strftime('%Y-%m-%dT%H:%M'), required: true %>
        <%= f.text_area :observation, value: @reminder.observation %>
      </div>
      <div class="modal-footer">
        <%= link_to "Delete",
                    {:controller => :reminders, :action => 'destroy', :id => @reminder.id },
                    :method => :delete, class: "btn btn-danger"
        %>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= f.submit "Save changes", :class => "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/reminders/_new.html.erb
<div class="modal-dialog" role="document">
  <%= bootstrap_form_for(:reminder, :url => url_for(:controller => 'reminders', :action => 'create') ) do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Create reminder</h5>
        <button type="button" class="btn close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= f.text_field :name, required: true, maxlength: "30" %>
        <%= f.color_field :color, required: true, value: "#FF0000" %>
        <%= f.datetime_field :date, value: @day.strftime('%Y-%m-%dT%H:%M'), required: true %>
        <%= f.text_area :observation %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= f.submit "Save changes", :class => "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/reminders/index.html.erb
<%= stylesheet_link_tag "reminders" %>

<div class="container mt-5">
  <% if flash[:errors] or flash[:notice] %>
    <div class="messages mb-4">
      <% unless flash[:errors].nil?  %>
        <% flash[:errors].each do |error|%>
          <div class="alert alert-danger m-2" role="alert">
            <%= error %>
          </div>
        <% end %>
      <% end %>
      <% if flash[:notice] %>
        <div class="alert alert-success m-2" role="alert">
          <%= flash[:notice]  %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= calendar(attribute: :date, data: @reminders) do |date, reminders| %>
    <div class="into-day-container" data-day="<%= date.to_s %>">
      <span class="date"><%= date.day %></span>
      <% if reminders.any? %>
          <% reminders.each do |reminder| %>
            <div class="reminder" style="background: <%= reminder.color %>" data-id="<%= reminder.id %>">
              <%= reminder.name %> - <%= reminder.date.strftime('%H:%M') %>
            </div>
          <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="modal fade" id="modal-forms">

</div>


<script>
  $(document).ready(() => {
    const modalEl = $("#modal-forms")
    $('.into-day-container').on("click", function(){
        console.log("chamei errado")
        let day = $(this).data('day');
      $.ajax({
        url: `<%= new_reminder_path %>?day=${day}`,
        type: 'GET',
        success: (data) => {
          modalEl.html(data);
          modalEl.modal('show')
        }
      });
    });
    $(".reminder").on("click", function (e) {
        e.stopPropagation()
        const id = $(this).data('id');
        const route = `<%= edit_reminder_path(":id") %>`
        $.ajax({
          url: route.replace(':id', id),
          type: 'GET',
          success: (data) => {
            modalEl.html(data);
            modalEl.modal('show')
          }
        });
    })
  })
</script>